### PR TITLE
Bundle update

### PR DESCRIPTION
**Pull request by ajm188**
Let's see what travis says

### CODE REVIEW

**Comment by matthewbentley** [comment]
It looks like some test is breaking...I'll look into it tomorrow...

**Comment by ajm188** [comment]
This looks related to a kaminari bump:

```haml
app/views/courses/index.html.haml:39
= page_entries_info @courses, class: 'crs_count'
```

```
Background:                               # features/course_explorer.feature:6
    Given I have authenticated as some user # features/step_definitions/shared_steps.rb:1
      unknown keyword: class (ActionView::Template::Error)
      ./app/views/courses/index.html.haml:39:in `_app_views_courses_index_html_haml__4053357285800149792_58683000'
      ./features/step_definitions/shared_steps.rb:10:in `/^I have authenticated as (.*)$/'
      features/course_explorer.feature:7:in `Given I have authenticated as some user'
```

**Comment by ajm188** [comment]
Indeed it would appear that the [interface to that method](https://github.com/kaminari/kaminari/blob/5df6c42ec8630fec12b43bae3eba35a8e33ac188/kaminari-core/lib/kaminari/helpers/helper_methods.rb#L100) has changed.

I'll look at the CSS/JS and see how badly we need that class name, then decide what to do.

**Comment by ajm188** [comment]
Fun fact, that class was not being rendered - ever. 
screen shot 2017-02-05 at 7 26 53 am

So, I'm just gonna remove it.

**Comment by ajm188** [comment]
I guess I should actually set up a local environment to test ...

**Comment by ajm188** [comment]
@matthewbentley should be good to go now; I opened a separate issue for the flaky test (#234)

Maybe @JKobyP would want to grab that one?

**Pull request merged**
