### PR TITLE
Fixes autocomplete issues on firefox (issue #115)

### PR DESCRIPTION
**Pull request by bhc24**

### CODE REVIEW

**Comment by ajm188** [comment]
This is failing because you don't have the up-to-date .travis.yml file. Merge from master, and it should pass.

**Comment by StephHippo** [comment]
@bhc24 if you haven't already, run git pull origin master, and then push again.

**Comment by StephHippo** [comment]
Checked this out again today and merged it to master. Still not sure all the autocomplete stuff works on firefox.

**Comment by ajm188** [comment]
It's not actually for autocomplete, just the text boxes. Do you want to push your merge commit here so the build passes?

**Comment by ajm188** [comment]
:+1:

**Pull request merged**
