### PR TITLE
adding a hound config

### PR DESCRIPTION
**Pull request by ajm188**

### CODE REVIEW

**Comment by ajm188** [comment]
I guess hound worked? Not really sure. @StephHippo

**Comment by StephHippo** [comment]
:+1: Good enough for me. Try making a style violation and see what happens?

**Comment by ajm188** [comment]
Will do. I'll put that commit in here, so don't merge yet. If it doesn't catch the style error, I say we just ditch hound.

**Comment by ajm188** [comment]
So if I run `rubocop app/models`, it finds 41 offenses... not exactly sure what hound is doing then.

**Comment by StephHippo** [comment]
:+1: It caught it's first violation, so this is definitely good to go.

**Pull request merged**
