### PR TITLE
Tips and reviews

### PR DESCRIPTION
**Pull request by ajm188**
This is not ready for merge yet for 2 reasons:
1. UI is ugly. Please give feedback.
2. Currently, a user can vote on a review as often as he/she wants. This means people can skew how helpful reviews are just by voting for their own a bunch of times. Is this okay, or do we want to pull the voting data out to another table to keep track of who has voted for what?

### CODE REVIEW

**Comment by StephHippo** [comment]
Don't let people vote more than once. People are jerks.

**Comment by ajm188** [comment]
:+1: Will work on that

**Comment by ajm188** [comment]
Can people vote to offset their previous vote? Meaning if I +1 something, but decide later I changed my mind, I can then go back and -1?

**Comment by ajm188** [comment]
Hey @StephHippo I haven't been able to get that feature test to fail locally, and looking at the test, it seems fine. I'm just going to restart the build and see if it passes, but I wanted to let you know in case you wanted to take a look at it.

**Comment by StephHippo** [comment]
Sorry, I've been meaning to review this. Will take a peek this weekend.

**Comment by StephHippo** [comment]
Something's wrong here. I fetched, switched to the branch, and ran migrations. Started up the app. Can't login. Can't see anything for Tips and Reviews.

**Comment by StephHippo** [comment]
jk now I can. Reviewing now. Please hold.

**Comment by StephHippo** [comment]
1. Doesn't look right on mobile. 
screen shot 2015-05-19 at 9 38 04 pm
2. Should get an option to just undo your vote in case you accidentally click it without forcing you to choose the opposite vote. If I accidentally upvote it, but I want to just undo the upvote, not downvote it. (Really surprised there isn't a gem for something like this.)
3. UI needs some work. Padding around the text box would be a good start, as well as a stylized dropdown.

**Comment by StephHippo** [comment]
Also, we should discussed if we want to show who left the review. My biggest concern with this feature is abuse. I'm really not okay with people using this to tear professors down. There are plenty of ways to leave a fair and honest review without being a dick, and when given anonymity, people are going to prefer the dick route.

**Comment by StephHippo** [comment]
Sorry about the tons of emails this is going to generate.

Also it's showing the lowest rated review first. Not what we want.
screen shot 2015-05-19 at 9 45 31 pm

But what if there was a system where if your review is downvoted too much, it's removed.
After you've had so many reviews removed, your privilege to reviews gets suspended, reported to use, and reviewed. 

This might seem like it's over complicating things, but it'll help silence the jerks quickly. The absolute last thing I want is for TJA to become a breeding ground for abuse. Honest and respectful reviews only.

**Comment by thomasrussellmurphy** [comment]
Check-in: @ajm188, are you still working on this feature?

**Comment by ajm188** [comment]
Ha yes I'll come back to this next week

**Comment by matthewbentley** [comment]
Necrobump: what's the status of this?

I'm not sure what the original scope of this feature was, but there has been discussion in USG recently about a system to leave comments/tips on courses/professors (and this might fit that nicely?).

**Comment by ajm188** [comment]
This branch is probably too stale to be much use. Also, I wasn't thrilled with parts of the implementation. I'm happy to take a second swing at it, but honestly I'd rather someone still at CWRU work on this feature, with me to review changes/provide feedback/etc.

**Pull request closed without merging**
