### PR TITLE
Converts site/faq to ERB

### PR DESCRIPTION
**Pull request by ajm188**

### CODE REVIEW

**Comment by matthewbentley** [comment]
There's got to be a (semi-)automated way to do these...it's all very predictable

**Comment by ajm188** [comment]
@matthewbentley there _probably_ is but I'm not sure

I know there's a tool for going ERB => haml, but I don't know about going the other way

**Comment by ajm188** [comment]
@StephHippo you didn't look at all the PRs :(

**Comment by StephHippo** [comment]
I thought I got everything that was assigned to me. Will do another glance
tonight.

**Comment by ajm188** [comment]
@StephHippo how did you look at every other PR but this one lol

**Comment by StephHippo** [comment]
*facepalm* lol GitHub really needs a better UX for seeing what I have left.

On Fri, Mar 10, 2017 at 8:35 AM Andrew Mason <notifications@github.com>
wrote:

@StephHippo <https://github.com/StephHippo> how did you look at every other
PR but this one lol

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/hacsoc/the_jolly_advisor/pull/248#issuecomment-285717249>,
or mute the thread

**Comment by ajm188** [comment]
@StephHippo https://github.com/hacsoc/the_jolly_advisor/pulls/review-requested/stephhippo

**Comment by StephHippo** [comment]
https://media.giphy.com/media/pEjnnil9lLrUc/200.gif

**Pull request merged**
