### PR TITLE
reconfigure coveralls

### LINKED ISSUE #62: Coveralls could use some more configuring
It's doing coverage analysis on a lot of files that it shouldn't... namely the entire config/ and spec/ directories

### PR DESCRIPTION
**Pull request by ajm188**
closes #62

### CODE REVIEW

**Comment by StephHippo** [comment]
Not merging this until you sleep.

**Comment by ajm188** [comment]
We're also not merging this until it's correct :smile: :sleeping:

**Comment by ajm188** [comment]
Much better. Coverage went down (because we're not getting false 100%'s from files in config/ and spec/), but it's actually looking at the right files now.

**Comment by ajm188** [comment]
For future reference, I got the information for merging coveralls info from http://blog.codeship.com/codeship-code-coverage-coveralls/

**Comment by StephHippo** [comment]
Okay fine :+1: And also cool.

**Pull request merged**
