### PR TITLE
List semesters on the show course page in newest to oldest order

### PR DESCRIPTION
**Pull request by matthewbentley**
Fixes a personal pet peeve.

### CODE REVIEW

**Comment by matthewbentley** [comment]
`reverse` seems to not be defined (but `reverse_each` is)

**Comment by ajm188** [comment]
Yeah I didn't realize it was a hash. Hmmm one sec

**Comment by ajm188** [comment]
I think instead of making the change in the view, we should change the query that the controller is doing.

See what you get with something like `@instances_by_semester = blah.blah.group_by(:semester).order(semester: :desc)`

**Comment by matthewbentley** [comment]
nope, `order` isn't defined

**Comment by ajm188** [comment]
As discussed on slack, revert the changes I asked for and we're good to go

**Pull request merged**
