### PR TITLE
fix Flakiness

### LINKED ISSUE #180: Flaky feature tests
Here are the ones I've identified so far:
- [x] "I can navigate to Course Show Page"
- [x] "Search by Professor"
- [x] "Search by keyword in a course description"

edit: found another one locally

### PR DESCRIPTION
**Pull request by ajm188**
closes #180

### CODE REVIEW

**Comment by ajm188** [comment]
See commit messages for explanations of the flakiness. The diffs should then be self-explanatory

**Comment by StephHippo** [comment]
This also looks good. :ship: :it:

**Comment by ajm188** [comment]
There's one more flaky test I found that I want to fix first. I'll post an update after I take a look at it.

**Comment by ajm188** [comment]
@StephHippo: updated. Here is the failure it fixes:

```
Scenario: Search by keyword in a course description
undefined method `split' for nil:NilClass (NoMethodError) ./features/step_definitions/course_explorer_steps.rb:60
```

**Comment by ajm188** [comment]
Poke for update.

_Really_ want to get this merged b/c re-running `rake` for flaky tests is driving me crazy.

**Comment by StephHippo** [comment]
:+1:

**Pull request merged**
