### PR TITLE
Active tab

### PR DESCRIPTION
**Pull request by ajm188**

### CODE REVIEW

**Comment by ajm188** [comment]
@Aghassi how does this look to you?

**Comment by Aghassi** [comment]
So I have two CSS gripes with this. Very minor though. The first is that the active tab has some space between it, the navigation bar, and the page. See attached image: 
screen shot 2016-05-18 at 8 27 43 pm

The other thing is if you select the account button in the top right and remove your cursor from it, you can't see the person in it because it doesn't stay highlighted.
screen shot 2016-05-18 at 8 30 38 pm

**Comment by ajm188** [comment]
> The first is that the active tab has some space between it, the navigation bar, and the page.

👍 trying to fix

> The other thing is if you select the account button in the top right and remove your cursor from it, you can't see the person in it because it doesn't stay highlighted.

This is a separate issue, actually. If you want to open a new issue and work on it (I'm not sure immediately how to fix it), you're more than welcome to!

**Comment by ajm188** [comment]
@Aghassi updated

**Comment by Aghassi** [comment]
@ajm188 Cool. The tabs look good. Other nit picky thing is don't have "Get Jolly" highlight when rolling over (I think if you set it to a banner or something assuming you are using bootstrap, should be fine). Also, is there a way to keep the highlighting of the user and the arrow on the preferences drop down once clicked?

**Comment by StephHippo** [comment]
Gonna let Aghassi approve this because he's better at front-end stuff, but otherwise LGTM.

**Pull request closed without merging**
