### PR TITLE
adding support for creating enrollments without autocomplete

### LINKED ISSUE #85: Searching without Autocomplete
When searching in the top bar's `Course Select` text box, if the user doesn't interact with the autocomplete and presses `return`, they should be sent to a search with the text they just entered as the query term.
Current behavior: the page reloads when `return` is pressed and the text disappears from the `Course Select` box.

### PR DESCRIPTION
**Pull request by ajm188**
This will officially close #85

### CODE REVIEW

**Comment by ajm188** [comment]
I'm not folding on the hash syntax for if, because most editors mark that as the keyword `if` and not the symbol in the new syntax.

**Comment by ajm188** [comment]
Also we should fix the hound config to allow our form of method chaining across lines, since it's way more readable than what hound wants.

Ex.
Hound doesn't like:
```ruby
Course.where(conditions)
      .order(columns)
```
And instead wants:
```ruby
Course.where(conditions).
       order(columns)
```

Which to me is less readable.

**Comment by StephHippo** [comment]
Agreed. Config is huge though. We should set aside some time to go through
it.

**Comment by ajm188** [comment]
@StephHippo am I fixing the style config on this PR or are we merging this and doing that later?

**Comment by StephHippo** [comment]
:+1:  Hound can wait. It's the configs, not you. #mergeitshipit

**Pull request merged**
