### PR TITLE
`bundle update rails`

### PR DESCRIPTION
**Pull request by ajm188**

### CODE REVIEW

**Comment by matthewbentley** [comment]
Internet is too slow for a proper review, so :+1: via email. As long as you
verified it works in dev.

On Jun 1, 2017 5:56 PM, "Andrew Mason" <notifications@github.com> wrote:

@ajm188 <https://github.com/ajm188> requested your review on:
hacsoc/the_jolly_advisor#257
<https://github.com/hacsoc/the_jolly_advisor/pull/257> bundle update rails.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/hacsoc/the_jolly_advisor/pull/257#event-1106328782>,
or mute
the thread

**Comment by ajm188** [comment]
@matthewbentley mind logging on and clicking the button sometime this week?
tor. 1. jun. 2017 kl. 12.31 skrev Matthew <notifications@github.com>:

> Internet is too slow for a proper review, so :+1: via email. As long as you
> verified it works in dev.
>

**Comment by greysteil** [comment]
@ajm188 - noticed you've created a couple of PRs like this one. Would you be up for beta testing a tool a friend and I have written to automate it (dependency updates)? (No link as I don't want to spam!) Obviously totally free for open-source, and always will be.

**Comment by ajm188** [comment]
@greysteil sure, I'd be interested. Can you link it, though? Or submit a PR/whatever to set up this mysterious tool? So I can see what's involved.

**Comment by greysteil** [comment]
Haha, of course - it's [here](https://dependabot.com). Example PR [here](https://github.com/ministryofjustice/prison-visits-2/pull/899). Possibly I'm being a bit too paranoid about spamming!

Would love your feedback!

**Comment by ajm188** [comment]
> Possibly I'm being a bit too paranoid about spamming!

I agree 😛 . Thanks for the info. I'm checking it out now. I'll let you know if I have any questions.

**Pull request merged**
