### PR TITLE
Tests with docker compose

### PR DESCRIPTION
**Pull request by ajm188**
We can run tests inside docker containers! Both locally and in travis

This is based on #233 , simply because I liked having the updated bundle

### CODE REVIEW

**Comment by ajm188** [comment]
@matthewbentley do you have any feedback on the naming, docker-compose specific stuff?

**Comment by matthewbentley** [comment]
It looked OK at first glance, but I'll go through in a little more detail right now.

**Comment by matthewbentley** [comment]
Yeah, still looks good. 👍

**Comment by ajm188** [comment]
idk why github hasn't picked up on the fact that the first four commits in this branch are now in master... gonna rebase, might need you to "re-approve"

**Comment by ajm188** [comment]
Guess not. Merging away

**Pull request merged**
