### PR TITLE
Upgrade Ruby, get docker stuff ready

### PR DESCRIPTION
**Pull request by matthewbentley**
I don't expect this to be merged right away (or at all), but this will (should) run the latest version of Ruby against the Travis system

### CODE REVIEW

**Comment by ajm188** [comment]
Looks good to me. I just want to get feedback, mainly from @StephHippo about changing dev environments close to the presentation date.

**Comment by StephHippo** [comment]
Yeah I'm not going to poke the bear this close to the presentation, but
Tuesday April 28th at 10:05 a.m., this can go live.

**Comment by ajm188** [comment]
Also, for GitHub purposes, this closes #71

**Comment by matthewbentley** [comment]
Cool, it looks like the pull request updates when I rebase and force push my commits.

**Comment by ajm188** [comment]
Yeah, and the CI hooks still fire, too.

**Comment by matthewbentley** [comment]
This also closes #70 (mostly, except for the defaults part)

**Comment by matthewbentley** [comment]
If there are no objections, I'll merge this right after the project presentations

**Comment by ajm188** [comment]
Go for it.

**Pull request merged**
